export default function Page() {
    return <>
        <h1 id="privacy-policy">Privacy Policy</h1>
        <p><strong>Effective date:</strong> 08/14/2024</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="introduction">Introduction</h2>
        <p>Welcome to Drake Rossman.</p>
        <p>Drake Rossman (“us”, “we”, or “our”) operates <a
            href="https://nixosbook.com">https://nixosbook.com</a> (hereinafter
            referred to as “Service”).</p>
        <p>Our Privacy Policy governs your visit to <a
            href="https://nixosbook.com">https://nixosbook.com</a> and explains how
            we collect, safeguard, and disclose information that results from your
            use of our Service.</p>
        <p>We use your data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this Privacy
            Policy, the terms used have the same meanings as in our Terms and
            Conditions.</p>
        <p>Our Terms and Conditions (“Terms”) govern all use of our Service and,
            together with the Privacy Policy, constitute your agreement with us
            (“agreement”).</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="definitions">Definitions</h2>
        <ul>
            <li><strong>SERVICE</strong> means the <a
                href="https://nixosbook.com">https://nixosbook.com</a> website operated
                by Drake Rossman.</li>
            <li><strong>PERSONAL DATA</strong> means data about a living individual
                who can be identified from those data (or from those and other
                information either in our possession or likely to come into our
                possession).</li>
            <li><strong>USAGE DATA</strong> is data collected automatically, either
                generated by the use of the Service or from the Service infrastructure
                itself (for example, the duration of a page visit).</li>
            <li><strong>DATA CONTROLLER</strong> means a natural or legal person who
                (either alone or jointly or in common with other persons) determines the
                purposes for which and the manner in which any personal data are, or are
                to be, processed. For the purpose of this Privacy Policy, we are a Data
                Controller of your data.</li>
            <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
                natural or legal person who processes the data on behalf of the Data
                Controller. We may use the services of various Service Providers to
                process your data more effectively.</li>
            <li><strong>DATA SUBJECT</strong> is any living individual who is the
                subject of Personal Data.</li>
            <li><strong>THE USER</strong> is the individual using our Service. The
                User corresponds to the Data Subject, who is the subject of Personal
                Data.</li>
        </ul>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="information-collection-and-use">Information Collection and
            Use</h2>
        <p>We collect several different types of information for various
            purposes to provide and improve our Service to you.</p>
        <h3 id="types-of-data-collected">Types of Data Collected</h3>
        <h4 id="personal-data">Personal Data</h4>
        <p>While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information may
            include, but is not limited to:</p>
        <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
        </ul>
        <p>We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials, and other information that may be of
            interest to you. You may opt out of receiving any, or all, of these
            communications from us by following the unsubscribe link or by emailing
            us at drake.rossman@protonmail.com.</p>
        <h4 id="usage-data">Usage Data</h4>
        <p>We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (“Usage Data”).</p>
        <p>This Usage Data may include information such as your computer’s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date of
            your visit, the time spent on those pages, unique device identifiers,
            and other diagnostic data.</p>
        <p>When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you use,
            unique device identifiers, and other diagnostic data.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="use-of-data">Use of Data</h2>
        <p>Drake Rossman uses the collected data for various purposes:</p>
        <ul>
            <li>To provide and maintain our Service;</li>
            <li>To notify you about changes to our Service;</li>
            <li>To allow you to participate in interactive features of our Service
                when you choose to do so;</li>
            <li>To provide customer support;</li>
            <li>To gather analysis or valuable information so that we can improve
                our Service;</li>
            <li>To monitor the usage of our Service;</li>
            <li>To detect, prevent and address technical issues;</li>
            <li>To fulfill any other purpose for which you provide it;</li>
            <li>To carry out our obligations and enforce our rights arising from any
                contracts entered into between you and us, including for billing and
                collection;</li>
            <li>To provide you with notices about your account and/or subscription,
                including expiration and renewal notices, email-instructions, etc.;</li>
            <li>To provide you with news, special offers, and general information
                about other goods, services, and events which we offer that are similar
                to those that you have already purchased or enquired about unless you
                have opted not to receive such information;</li>
            <li>In any other way we may describe when you provide the
                information;</li>
            <li>For any other purpose with your consent.</li>
        </ul>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="retention-of-data">Retention of Data</h2>
        <p>We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and use
            your Personal Data to the extent necessary to comply with our legal
            obligations (for example, if we are required to retain your data to
            comply with applicable laws), resolve disputes, and enforce our legal
            agreements and policies.</p>
        <p>We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this data
            is used to strengthen the security or to improve the functionality of
            our Service, or we are legally obligated to retain this data for longer
            time periods.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="transfer-of-data">Transfer of Data</h2>
        <p>Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state, province,
            country, or other governmental jurisdiction where the data protection
            laws may differ from those of your jurisdiction.</p>
        <p>If you are located outside the United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to the United States and process it there.</p>
        <p>Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.</p>
        <p>Drake Rossman will take all the steps reasonably necessary to ensure
            that your data is treated securely and in accordance with this Privacy
            Policy, and no transfer of your Personal Data will take place to an
            organization or a country unless there are adequate controls in place
            including the security of your data and other personal information.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="disclosure-of-data">Disclosure of Data</h2>
        <p>We may disclose personal information that we collect, or you
            provide:</p>
        <h3 id="other-cases">Other cases</h3>
        <p>We may disclose your information also:</p>
        <ul>
            <li>To contractors, service providers, and other third parties we use to
                support our business;</li>
        </ul>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="security-of-data">Security of Data</h2>
        <p>The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic storage
            is 100% secure. While we strive to use commercially acceptable means to
            protect your Personal Data, we cannot guarantee its absolute
            security.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }}
            id="your-data-protection-rights-under-general-data-protection-regulation-gdpr">Your
            Data Protection Rights Under General Data Protection Regulation
            (GDPR)</h2>
        <p>If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights, covered by
            GDPR. – See more at <a
                href="https://eur-lex.europa.eu/eli/reg/2016/679/oj">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a>.</p>
        <p>We aim to take reasonable steps to allow you to correct, amend,
            delete, or limit the use of your Personal Data.</p>
        <p>If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please email us at
            drake.rossman@protonmail.com.</p>
        <p>In certain circumstances, you have the following data protection
            rights:</p>
        <ul>
            <li>The right to access, update, or delete the information we have on
                you;</li>
            <li>The right of rectification. You have the right to have your
                information rectified if that information is inaccurate or
                incomplete;</li>
            <li>The right to object. You have the right to object to our processing
                of your Personal Data;</li>
            <li>The right of restriction. You have the right to request that we
                restrict the processing of your personal information;</li>
            <li>The right to data portability. You have the right to be provided
                with a copy of your Personal Data in a structured, machine-readable, and
                commonly used format;</li>
            <li>The right to withdraw consent. You also have the right to withdraw
                your consent at any time where we rely on your consent to process your
                personal information;</li>
        </ul>
        <p>Please note that we may ask you to verify your identity before
            responding to such requests. Please note, we may not be able to provide
            Service without some necessary data.</p>
        <p>You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="service-providers">Service Providers</h2>
        <p>We may employ third party companies and individuals to facilitate our
            Service (“Service Providers”), provide Service on our behalf, perform
            Service-related services or assist us in analysing how our Service is
            used.</p>
        <p>These third parties have access to your Personal Data only to perform
            these tasks on our behalf and are obligated not to disclose or use it
            for any other purpose.</p>
        <h3 id="analytics">Analytics</h3>
        <p>We may use third-party Service Providers to monitor and analyze the
            use of our Service.</p>
        <h4 id="goatcounter">GoatCounter</h4>
        <p>GoatCounter is an open source website analytics platform. For
            more information about GoatCounter, please visit their Privacy Policy:
            https://www.goatcounter.com/help/privacy</p>
        <h3 id="payments">Payments</h3>
        <p>We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g. payment
            processors).</p>
        <p>We will not store or collect your payment card details. That
            information is provided directly to our third-party payment processors
            whose use of your personal information is governed by their Privacy
            Policy. These payment processors adhere to the standards set by PCI-DSS
            as managed by the PCI Security Standards Council, which is a joint
            effort of brands like Visa, Mastercard, American Express and Discover.
            PCI-DSS requirements help ensure the secure handling of payment
            information.</p>
        <p>The payment processors we work with are:</p>
        <h4 id="paddle">Paddle:</h4>
        <p>Their Privacy Policy can be viewed at:
            https://www.paddle.com/legal/privacy</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="links-to-other-sites">Links to Other Sites</h2>
        <p>Our Service may contain links to other sites that are not operated by
            us. If you click a third party link, you will be directed to that third
            party’s site. We strongly advise you to review the Privacy Policy of
            every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content,
            privacy policies or practices of any third party sites or services.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="childrens-privacy">Children’s Privacy</h2>
        <p>Our Services are not intended for use by children under the age of 13
            (“Children”).</p>
        <p>We do not knowingly collect personally identifiable information from
            Children under 13. If you become aware that a Child has provided us with
            Personal Data, please contact us. If we become aware that we have
            collected Personal Data from Children without verification of parental
            consent, we take steps to remove that information from our servers.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="changes-to-this-privacy-policy">Changes to This Privacy
            Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update “effective
            date” at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.</p>
        <br></br>
        <h2 style={{ fontWeight: 'bold' }} id="contact-us">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact
            us:</p>
        <p>By email: drake.rossman@protonmail.com.</p>
    </>
}
